# Generated by Django 4.2.2 on 2023-06-11 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('Art', 'Art'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Politics', 'Politics'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Research', 'Research'), ('Other', 'Other')], default='Other', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
    ]
