# Generated by Django 4.2.2 on 2023-06-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beta_product", "0003_alter_userinterest_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Art", "Art"),
                    ("Business", "Business"),
                    ("Education", "Education"),
                    ("Entertainment", "Entertainment"),
                    ("Health", "Health"),
                    ("Politics", "Politics"),
                    ("Science", "Science"),
                    ("Sports", "Sports"),
                    ("Technology", "Technology"),
                    ("Research", "Research"),
                    ("Other", "Other"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
